package com.example.aloqa_kompaniya.entity.enums;

public enum PermissionEnum {

    ADD_MOBILEOPERATOR,
    READ_MOBILEOPERATOR,
    EDIT_MOBILEOPERATOR,
    DELETE_MOBILEOPERATOR,
    ADD_TARIFF,
    READ_TARIFF,
    EDIT_TARIFF,
    DELETE_TARIFF,
    ADD_COMPANY,
    READ_COMPANY,
    EDIT_COMPANY,
    DELETE_COMPANY,
    ADD_EMPLOYEE,
    READ_EMPLOYEE,
    EDIT_EMPLOYEE,
    DELETE_EMPLOYEE,
    ADD_FILIAL,
    READ_FILIAL,
    EDIT_FILIAL,
    DELETE_FILIAL,
    ADD_SIMCARD,
    READ_SIMCARD,
    EDIT_SIMCARD,
    DELETE_SIMCARD
}
